### PR TITLE
Exposed API for querying earliest offset past a timestamp

### PR DESCRIPTION
**Pull request by ajayrathore**

### CODE REVIEW

**Comment by ajayrathore** [comment]
Hi,
Is it possible this PR can be reviewed by someone?

Thanks,
Ajay

**Comment by cmccarthy1** [comment]
Hi Ajay,

Yes it's on my to-do list, I'll get to it later in the week.

If you could provide an example invocation too that would be extremely helpful with generating documentation.

All the best

**Comment by ajayrathore** [comment]
Below is an example invocation

`
\l kfk.q
// create consumer process within group 0
client:.kfk.Consumer[`metadata.broker.list`group.id!`localhost:9092`0];
// fetch first offset past midnight for partition 0
.kfk.OffsetsForTimes[client; `topic; enlist[0i]!enlist floor(`long$(.z.d+0t) - 1970.01.01D00)%1e6; 500]
`

**Comment by cmccarthy1** [comment]
Thanks Ajay.

I'll aim to review this by Thursday and suggest any potential modifications as required.

All the best

**Comment by cmccarthy1** [comment]
Looking at this now Ajay, from the C code side of things it looks good although it's very inflexible. My initial suggestions are the following changes although final code may change.
```
> kfk.c
- EXP K4(kfkOffsetsForTimes){
+ EXP K4(kfkoffsetForTime){

> kfk.q
- (`kfkOffsetsForTimes;4)
+ (`kfkoffsetForTime;4)

+ // Retrieval of offset associated with a specified time
+ /* cid is an integer denoting client id
+ /* top is the topic which is being queried
+ /* partoff is a dictionary mapping the partition to the offset being queried
+ /*   in this case offset can be a long denoting milliseconds since 1970.01.01, 
+ /*   a timestamp or date.
+ /* tout is the maximum timeout in milliseconds the function will block for
+ OffsetsForTimes:{[cid;top;partoff;tout]
+  if[6h<>type key partoff;'"'partoff' key must be an integer list"];
+  offsetType:type value partoff;
+  if[not offsetType in(7h;12h;14h);
+    '"'partoff' key must be a list of longs, timestamps or dates only"];
+  timeOffset:$[14h=offsetType;0t+;]partoff;
+  if[7h<>offsetType;timeOffset:floor(`long$timeOffset-1970.01.01D00)%1e6];
+  offsetForTime[cid;top;timeOffset;tout]
+  }
```
The above will support a user mapping partition to timestamp, date (assumes time you are requesting is midnight) and a long which is the number of milliseconds since

**Comment by ajayrathore** [comment]
Yes, your suggested changes look good to me and work as expected.

Thanks,
Ajay

**Comment by cmccarthy1** [comment]
Ok great. I'll aim to have this merged in by end of week. We'll have an internal review of the addition and make any final changes as required before a merge.

All the best,

Conor

**Comment by ajayrathore** [comment]
Hi Conor

Whats the hold up now?

Thanks,
Ajay

**Comment by cmccarthy1** [comment]
Sorry Ajay, there were other issues that required attention from members of the team the last week I'll aim to get this integrated by close of business Friday.

**Review by mshimizu-kx — APPROVED** [review]
Good.

**Pull request merged**
